//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRIER_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARRIER_MASTER()
        {
            this.TRACKING_TABLE = new HashSet<TRACKING_TABLE>();
        }
    
        public int carrier_id { get; set; }
        public Nullable<int> tracking_id { get; set; }
        public string name { get; set; }
        public Nullable<int> contract_no { get; set; }
        public string dni { get; set; }
        public string address { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACKING_TABLE> TRACKING_TABLE { get; set; }
    }
}
