//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_MASTER()
        {
            this.PRODUCTS_TRACKING = new HashSet<PRODUCTS_TRACKING>();
        }
    
        public int product_id { get; set; }
        public Nullable<int> typproduct_id { get; set; }
        public string product_name { get; set; }
        public Nullable<bool> flg_perishable { get; set; }
    
        public virtual TYPPRODUCT_MASTER TYPPRODUCT_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTS_TRACKING> PRODUCTS_TRACKING { get; set; }
    }
}
