//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENSOR_MASTER
    {
        public string id_contrato { get; set; }
        public string codigoseguimiento { get; set; }
        public Nullable<decimal> temperatura { get; set; }
        public Nullable<decimal> humidity { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public int id_message { get; set; }
        public string id_sensor { get; set; }
    }
}
