//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tpEntities : DbContext
    {
        public tpEntities()
            : base("name=tpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BC> BC { get; set; }
        public virtual DbSet<CARRIER_MASTER> CARRIER_MASTER { get; set; }
        public virtual DbSet<CITY_MASTER> CITY_MASTER { get; set; }
        public virtual DbSet<PRODUCT_MASTER> PRODUCT_MASTER { get; set; }
        public virtual DbSet<PRODUCTS_TRACKING> PRODUCTS_TRACKING { get; set; }
        public virtual DbSet<TRACKING_TABLE> TRACKING_TABLE { get; set; }
        public virtual DbSet<TYPPRODUCT_MASTER> TYPPRODUCT_MASTER { get; set; }
        public virtual DbSet<USER_MASTER> USER_MASTER { get; set; }
        public virtual DbSet<SENSOR_MASTER> SENSOR_MASTER { get; set; }
    }
}
