//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_MASTER()
        {
            this.TRACKING_TABLE = new HashSet<TRACKING_TABLE>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public Nullable<int> contract_no { get; set; }
        public string user_type { get; set; }
        public string ruc { get; set; }
        public string razon_social { get; set; }
        public string location { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACKING_TABLE> TRACKING_TABLE { get; set; }
    }
}
